routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('login', function () {
    return view('login');
})->name('login');;




Route::get('/', function () {
    if(auth()->user())
    {
        return redirect('dashboard2');
    }
    else
    {
        return view('login');
    }
});

Route::post('login', 'Auth\LoginController@login');


Route::middleware('auth')->group(function () {

            Route::get('logout', 'Auth\LoginController@logout');

            Route::get('dashboard2', 'DashboardController@dashboard');
            Route::post('searchDashboard', 'DashboardController@searchDashboard');

            Route::get('staff2', 'DashboardController@staff');
            Route::get('sasstaffassign/{id}', 'DashboardController@showSAS');
            Route::post('searchSAS', 'DashboardController@searchSAS');

            Route::get('equipment2', 'DashboardController@equipment');
            Route::get('ebs/{id}', 'DashboardController@showEBS');    
            Route::post('searchEBS', 'DashboardController@searchEBS');

            Route::get('transport2', 'DashboardController@transport');
            Route::get('tbs/{id}', 'DashboardController@showTBS');  
            Route::post('searchTBS', 'DashboardController@searchTBS'); 

            Route::get('maintenance2', 'DashboardController@maintenance');
            Route::get('mss/{id}', 'DashboardController@showMSS');   
            Route::post('searchMSS', 'DashboardController@searchMSS'); 

            Route::get('tender2', 'DashboardController@tender');
            Route::get('tms/{id}', 'DashboardController@showTMS');   
            Route::post('searchTMS', 'DashboardController@searchTMS'); 

    

            Route::get('/dashboard', function () {
                return view('dashboard');
            });

            Route::get('/staff', function () {
                return view('staffAssignmentSystem');
            });

            Route::get('/equipment', function () {
                return view('equipment');
            });

            Route::get('/transport', function () {
                return view('transport');
            });

            Route::get('/maintenance', function () {
                return view('maintenance');
            });

            Route::get('/tender', function () {
                return view('tender');
            });

});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\URL;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    protected $table = 'users';
    public $incrementing = FALSE;
    protected $with = ['role', 'inquiry', 'document_log'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->hasOne('App\Role', 'id', 'id_role');
    }

    public function getImgPathAttribute($value)
    {
        $url = URL::to($value);
        return $url;
    }

    public function inquiry()
    {
        return $this->hasOne('App\InquiryType', 'id', 'id_inquiry');
    }

    public function document_log()
    {
        return $this->hasMany('App\DocumentLog', 'id_user', 'id');
    }

    public function ebs()
    {
        return $this->belongsToMany('App\EBS', 'ebs_staff_uses', 'id_user', 'id_ebs');
    }

    public function ebs_booking()
    {
        return $this->hasMany('App\EBSStaffUse', 'id_user');
    }

    public function assignDaily($date)
    {
        return $this->hasMany('App\SASStaffAssign', 'id_user')
            ->whereRaw('? between date(sas_staff_assigns.start_date) and sas_staff_assigns.end_date', [$date])
            ->get();
    }

    public function assignMonthly($month)
    {
        return $this->hasMany('App\SASStaffAssign', 'id_user')
            ->whereMonth('sas_staff_assigns.start_date', $month)
            ->get();
    }
}

resources/views/equipment2.blade.php
@extends('layouts.app')

@push('styles')
    
@endpush

@section('content')



<div class="row" style="padding-bottom:20px;padding-top:20px">
  <div class="col-lg-12">
    <h3><strong>Equipment Booking System</strong></h3>
  </div>
</div>

<div class="row">
  <div class="col-lg-8">
    <div class="card">
      <div class="card-body">

          <div class="row">
            <div class="col-lg-6">
              <h4 class="card-title" style="font-weight:bold">Calendar</h4>
            </div>
            <div class="col-lg-6 text-right">
              <img src="{{URL::to('vector/calendar.svg')}}">
            </div>
          </div>

          {!! Form::open(['action' => 'DashboardController@searchEBS', 'method' => 'POST','class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
          @csrf

          <div class="row">
            <div class="col-lg-6">
              <table style="width:100%">
                <tr>
                  <td>
                    <select class="select2 form-control custom-select" style="width: 100%; height:36px;" id="equipment" name="equipment">
                      @if (isset($curr_equipment))
                        <option value="{{$curr_equipment->id}}">{{$curr_equipment->name}}</option>
                      @else
                        <option value="">Select Equipment</option>
                      @endif
                      
                      @foreach ($equipments as $equipment)
                        <option value="{{$equipment->id}}">{{$equipment->name}}</option>
                      @endforeach
                    </select>
                  </td>
                  <td>
                    <button type="submit" class="btn waves-effect waves-light btn-danger" style="border-radius: 10px;"><i class="fas fa-search"></i> GO</button>
                  </td>
                </tr>
              </table>
            </div>
          </div>

          {!! Form::close() !!}

          <div id='calendar' style="padding:20px"></div>

      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

              <div class="row">
                <div class="col-lg-6">
                  <h4 class="card-title" style="font-weight:bold">Comment</h4>
                </div>
                <div class="col-lg-6 text-right">
                  <img src="{{URL::to('vector/bell.svg')}}">
                </div>
              </div>

              <div class="row">
                <div class="col-lg-12">
                  <h6 class="card-title  text-muted" style="font-weight:bold">No Comment Yet</h6>
                </div>
              </div>
        
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-lg-6">
                <h4 class="card-title" style="font-weight:bold">Recent Activities</h4>
              </div>
              <div class="col-lg-6 text-right">
                <img src="{{URL::to('img/activity.svg')}}">
              </div>
            </div>
           
            @if (count($documentLogs) > 0)
            <div class="card-body">
              <div class="row">
                <div class="col-lg-12 ps ps--theme_default ps--active-y" id="slimtest1" style="height: 580px;" data-ps-id="8db3e847-849b-2759-763b-e8592111f38d">
              <div class="profiletimeline">
                  @foreach ($documentLogs as $log)

                          <div class="sl-item">
                              <div class="sl-left"> <img src="{{$log->user ? $log->user->img_path : ""}}" alt="user" class="img-circle"> </div>
                              <div class="sl-right">
                                  <div><b style="font-weight: bold;">{{$log->user ? $log->user->name : ""}}</b>
                                      <span class="sl-date" style="float:right;font-weight: bold;">{{ Carbon\Carbon::parse($log->created_at)->diffForHumans()}} </span>
                                      <p class="m-t-10 text-muted" style="font-weight:500">{{$log->remark}}</p>
                                  </div>
                              </div>
                          </div>
                          <hr>
                  @endforeach
              </div>
              <div class="ps__scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                  <div class="ps__scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
              </div>
              <div class="ps__scrollbar-y-rail" style="top: 0px; height: 250px; right: 0px;">
                  <div class="ps__scrollbar-y" tabindex="0" style="top: 0px; height: 83px;"></div>
              </div>
            </div>
          </div>
          </div>
            @else
            <br><br><br>
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 text-center">
                    <img src="{{asset('img/no_log.png')}}" style="height:100%;width:100%;">
                </div>
            </div>
            <br><br><br>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h4 style='width:100%;font-weight:bold'>No Activity Yet</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p style='width:100%;' class="text-muted">Once activities has been create. It will appear here.</p>
                </div>
            </div>
            @endif

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>


<!-- Event Modal -->
<div id="eventModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel" style="font-weight:bold">Equipment Booking System(EBS) - Booking Detail</h4>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>
          <div class="modal-body">
             
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Close</button>
          </div>
      </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

@endsection

@push('scripts')
<script>

  document.addEventListener('DOMContentLoaded', function() {

    const events = @json($event);

    var calendarEl = document.getElementById('calendar');

    const ebsEvent = events.map(({
            start_date: start, 
            end_date: end, 
            job_title: title,
            id
    }, index)=>({
        start,
        end,
        title,
        id
    }))

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'dayGrid', 'timeGrid', 'list', 'interaction' ],
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      eventColor: '#ef5350',
      events: ebsEvent,
      eventTimeFormat: { // like '14:30:00'
        hour: 'numeric',
        minute: '2-digit',
        meridiem: 'short'
      },
      eventClick: function({event: {start, end, title, id}, el}) {
            const eventModal = $('#eventModal')
            eventModal.modal('show')
            const modalbody = eventModal.find('.modal-body')
            modalbody.html("<div><div class='row'><div class='col-lg-12 text-center'><div class='lds-facebook'><div></div><div></div><div></div></div></div></div><div class='row'><div class='col-lg-12 text-center'><strong>Loading...</strong></div></div></div>");

            modalbody.load(`/ebs/${id}`, function( response, status, xhr ) {
              if ( status == "error" ) {
                var msg = "Sorry but there was an error: ";
                modalbody.html( msg + xhr.status + " " + xhr.statusText );
              }

            });
        },
    });

    calendar.render();
  });

</script>

@endpush

resources/views/maintenance2.blade.php
@extends('layouts.app')

@push('styles')
    
@endpush

@section('content')



<div class="row" style="padding-bottom:20px;padding-top:20px">
  <div class="col-lg-12">
    <h3><strong>Maintenance Schedule System</strong></h3>
  </div>
</div>

<div class="row">
  <div class="col-lg-8">
    <div class="card">
      <div class="card-body">

          <div class="row">
            <div class="col-lg-6">
              <h4 class="card-title" style="font-weight:bold">Calendar</h4>
            </div>
            <div class="col-lg-6 text-right">
              <img src="{{URL::to('vector/calendar.svg')}}">
            </div>
          </div>
        
          {!! Form::open(['action' => 'DashboardController@searchMSS', 'method' => 'POST','class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
          @csrf

          <div class="row">
            <div class="col-lg-6">
              <table style="width:100%">
                <tr>
                  <td>
                    <select class="select2 form-control custom-select" style="width: 100%; height:36px;" id="maintenance" name="maintenance">
                      @if (isset($curr_task))
                          <option value="{{$curr_task->id}}">{{$curr_task->name}}</option>
                      @else
                          <option value="">Select Task</option>
                      @endif
                      
                        @foreach ($tasks as $task)
                          <option value="{{$task->id}}">{{$task->name}}</option>
                        @endforeach
                    </select>
                  </td>
                  <td>
                    <button type="submit" class="btn waves-effect waves-light btn-danger" style="border-radius: 10px;"><i class="fas fa-search"></i> GO</button>
                  </td>
                </tr>
              </table>
            </div>
          </div>

          {!! Form::close() !!}

          <div id='calendar' style="padding:20px"></div>

      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

              <div class="row">
                <div class="col-lg-6">
                  <h4 class="card-title" style="font-weight:bold">Comment</h4>
                </div>
                <div class="col-lg-6 text-right">
                  <img src="{{URL::to('vector/bell.svg')}}">
                </div>
              </div>
        
              <div class="row">
                <div class="col-lg-12">
                  <h6 class="card-title  text-muted" style="font-weight:bold">No Comment Yet</h6>
                </div>
              </div>

          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-lg-6">
                <h4 class="card-title" style="font-weight:bold">Recent Activities</h4>
              </div>
              <div class="col-lg-6 text-right">
                <img src="{{URL::to('img/activity.svg')}}">
              </div>
            </div>
           
            @if (count($documentLogs) > 0)
            <div class="card-body">
              <div class="row">
                <div class="col-lg-12 ps ps--theme_default ps--active-y" id="slimtest1" style="height: 580px;" data-ps-id="8db3e847-849b-2759-763b-e8592111f38d">
              <div class="profiletimeline">
                  @foreach ($documentLogs as $log)

                          <div class="sl-item">
                              <div class="sl-left"> <img src="{{$log->user ? $log->user->img_path : ""}}" alt="user" class="img-circle"> </div>
                              <div class="sl-right">
                                  <div><b style="font-weight: bold;">{{$log->user ? $log->user->name : ""}}</b>
                                      <span class="sl-date" style="float:right;font-weight: bold;">{{ Carbon\Carbon::parse($log->created_at)->diffForHumans()}} </span>
                                      <p class="m-t-10 text-muted" style="font-weight:500">{{$log->remark}}</p>
                                  </div>
                              </div>
                          </div>
                          <hr>
                  

                  @endforeach
              </div>
              <div class="ps__scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps__scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps__scrollbar-y-rail" style="top: 0px; height: 250px; right: 0px;">
                <div class="ps__scrollbar-y" tabindex="0" style="top: 0px; height: 83px;"></div>
            </div>
          </div>
        </div>
      </div>
            @else
            <br><br><br>
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 text-center">
                    <img src="{{asset('img/no_log.png')}}" style="height:100%;width:100%;">
                </div>
            </div>
            <br><br><br>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h4 style='width:100%;font-weight:bold'>No Activity Yet</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p style='width:100%;' class="text-muted">Once activities has been create. It will appear here.</p>
                </div>
            </div>
            @endif

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

<!-- Event Modal -->
<div id="eventModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel" style="font-weight:bold">Maintenance Schedule System (MSS) - Schedule Detail</h4>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>
          <div class="modal-body">
             
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Close</button>
          </div>
      </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

@endsection

@push('scripts')
<script>

  document.addEventListener('DOMContentLoaded', function() {

    const events = @json($event);

    var calendarEl = document.getElementById('calendar');

    const mssEvent = events.map(({
            start_date: start, 
            end_date: end, 
            description: title,
            id
    }, index)=>({
        start,
        end,
        title,
        id
    }))

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'dayGrid', 'timeGrid', 'list', 'interaction' ],
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      eventColor: '#ef5350',
      events: mssEvent,
      eventTimeFormat: { // like '14:30:00'
        hour: 'numeric',
        minute: '2-digit',
        meridiem: 'short'
      },
      eventClick: function({event: {start, end, title, id}, el}) {
            const eventModal = $('#eventModal')
            eventModal.modal('show')
            const modalbody = eventModal.find('.modal-body')
            modalbody.html("<div><div class='row'><div class='col-lg-12 text-center'><div class='lds-facebook'><div></div><div></div><div></div></div></div></div><div class='row'><div class='col-lg-12 text-center'><strong>Loading...</strong></div></div></div>");

            modalbody.load(`/mss/${id}`, function( response, status, xhr ) {
              if ( status == "error" ) {
                var msg = "Sorry but there was an error: ";
                modalbody.html( msg + xhr.status + " " + xhr.statusText );
              }

            });
      
        },
    });

    calendar.render();
  });

</script>

@endpush

resources/views/staffAssignmentSystem2.blade.php
@extends('layouts.app')

@push('styles')
    


@endpush

@section('content')



<div class="row" style="padding-bottom:20px;padding-top:20px">
  <div class="col-lg-12">
    <h3><strong>Staff Assignment System</strong></h3>
  </div>
</div>

<div class="row">
  <div class="col-lg-8">
    <div class="card">
      <div class="card-body">

          <div class="row">
            <div class="col-lg-6">
              <h4 class="card-title" style="font-weight:bold">Calendar</h4>
            </div>
            <div class="col-lg-6 text-right">
              <img src="{{URL::to('vector/calendar.svg')}}">
            </div>
          </div>

          {!! Form::open(['action' => 'DashboardController@searchSAS', 'method' => 'POST','class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
          @csrf

          <div class="row">
            <div class="col-lg-6">
              <table style="width:100%">
                <tr>
                  <td>
                    <select class="select2 form-control custom-select" style="width: 100%; height:36px;" id="staff" name="staff">
                      @if (isset($curr_user))
                        <option value="{{$curr_user->id}}">{{$curr_user->name}}</option>
                      @else
                        <option value="">Select Staff</option>
                      @endif
                      
                      @foreach ($users as $user)
                        <option value="{{$user->id}}">{{$user->name}}</option>
                      @endforeach
                    </select>
                  </td>
                  <td>
                    <button type="submit" class="btn waves-effect waves-light btn-danger" style="border-radius: 10px;"><i class="fas fa-search"></i> GO</button>
                  </td>
                </tr>
              </table>
            </div>
          </div>

          {!! Form::close() !!}

          <div id='calendar' style="padding:20px"></div>

      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

              <div class="row">
                <div class="col-lg-6">
                  <h4 class="card-title" style="font-weight:bold">Comment</h4>
                </div>
                <div class="col-lg-6 text-right">
                  <img src="{{URL::to('vector/bell.svg')}}">
                </div>
              </div>
        
              @if (count($sascomments) > 0)
                  <div class="card-body">
                    @foreach ($sascomments as $sascomment)
                         <!-- Comment item-->
                        <div class="activity-item" style="margin-bottom: 30px;">
                          <table width="100%">
                            <tr>
                              <td><div class="round m-r-20"><img src="{{$sascomment->usercomment ? $sascomment->usercomment->img_path : ''}}" alt="user" width="50"></div></td>
                              <td>
                                  <div class="m-t-10">
                                    <h5 class="m-b-5 font-medium"><b>{{$sascomment->usercomment ? $sascomment->usercomment->name : ''}}</b><span class="text-muted font-14 m-l-10">| &nbsp; {{ Carbon\Carbon::parse($sascomment->created_at)->diffForHumans()}}</span></h5>
                                    <h6 class="text-muted">Commented on <strong>{{$sascomment->sasstaffassign->user ? $sascomment->sasstaffassign->user->name : ''}} Task</strong></h6>
                                    <p class="m-b-0">{{$sascomment->comment}}</p>
                                </div>
                              </td>
                            </tr>
                          </table>
                        </div>
                        <!-- Comment item-->
                    @endforeach
                </div>
              @else
                <div class="row">
                  <div class="col-lg-12">
                    <h6 class="card-title  text-muted" style="font-weight:bold">No Comment Yet</h6>
                  </div>
                </div>
              @endif
              
              
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-lg-6">
                <h4 class="card-title" style="font-weight:bold">Recent Activities</h4>
              </div>
              <div class="col-lg-6 text-right">
                <img src="{{URL::to('img/activity.svg')}}">
              </div>
            </div>
           
            @if (count($documentLogs) > 0)
            <div class="card-body">
              <div class="row">
                <div class="col-lg-12 ps ps--theme_default ps--active-y" id="slimtest1" style="height: 580px;" data-ps-id="8db3e847-849b-2759-763b-e8592111f38d">
              <div class="profiletimeline">
                  @foreach ($documentLogs as $log)

                          <div class="sl-item">
                              <div class="sl-left"> <img src="{{$log->user ? $log->user->img_path : ""}}" alt="user" class="img-circle"> </div>
                              <div class="sl-right">
                                  <div><b style="font-weight: bold;">{{$log->user ? $log->user->name : ""}}</b>
                                      <span class="sl-date" style="float:right;font-weight: bold;">{{ Carbon\Carbon::parse($log->created_at)->diffForHumans()}} </span>
                                      <p class="m-t-10 text-muted" style="font-weight:500">{{$log->remark}}</p>
                                  </div>
                              </div>
                          </div>
                          <hr>
                  

                  @endforeach
              </div>
              <div class="ps__scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps__scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps__scrollbar-y-rail" style="top: 0px; height: 250px; right: 0px;">
                <div class="ps__scrollbar-y" tabindex="0" style="top: 0px; height: 83px;"></div>
            </div>
            </div>
          </div>
          </div>
            @else
            <br><br><br>
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 text-center">
                    <img src="{{asset('img/no_log.png')}}" style="height:100%;width:100%;">
                </div>
            </div>
            <br><br><br>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h4 style='width:100%;font-weight:bold'>No Activity Yet</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p style='width:100%;' class="text-muted">Once activities has been create. It will appear here.</p>
                </div>
            </div>
            @endif

          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>


<!-- Event Modal -->
<div id="eventModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel" style="font-weight:bold">Staff Assignment System(SAS) - Task Detail</h4>
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>
          <div class="modal-body">
             
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Close</button>
          </div>
      </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

@endsection

@push('scripts')
<script>

  document.addEventListener('DOMContentLoaded', function() {

    const events = @json($event);

    var calendarEl = document.getElementById('calendar');

    const sasEvent = events.map(({
            start_date: start, 
            end_date: end, 
            sas: {
              job_title: title,
            },
            id
    }, index)=>({
        start,
        end,
        title,
        id
    }))

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'dayGrid', 'timeGrid', 'list', 'interaction' ],
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      
      meridiem: 'short',
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      eventColor: '#ef5350',
      events: sasEvent,
      eventTimeFormat: { // like '14:30:00'
        hour: 'numeric',
        minute: '2-digit',
        meridiem: 'short'
      },
      eventClick: function({event: {start, end, title, id}, el}) {
            const eventModal = $('#eventModal')
            eventModal.modal('show')
            const modalbody = eventModal.find('.modal-body')
            modalbody.html("<div><div class='row'><div class='col-lg-12 text-center'><div class='lds-facebook'><div></div><div></div><div></div></div></div></div><div class='row'><div class='col-lg-12 text-center'><strong>Loading...</strong></div></div></div>");
            modalbody.load(`/sasstaffassign/${id}`, function( response, status, xhr ) {
              if ( status == "error" ) {
                var msg = "Sorry but there was an error: ";
                modalbody.html( msg + xhr.status + " " + xhr.statusText );
              }

            });
 
        },
    });

    calendar.render();
  });

</script>

@endpush